### ISSUE TITLE
API access using json format not working

### ISSUE THREAD

**Issue by dan-at-unkubed** [merchantos/api_samples#2]
I'm new to the API.  This library was great, but I wanted to use the json formatting for the returned data.  When I tried to do this, using the makeAPICall function call, it returned an error.  It looked like the library had only been coded to access the "xml" return format.  So, I altered a little of the code and it seems to be working great now.

I've not much experience doing the whole "pull request" thing, so I'll just include the code changes I made here:

File -- php/MOSAPI/MOSAPICall.class.php

    protected static function _makeCall($curl,$url,$xml,$emitter)
	{
		$result = $curl->call($url,$xml);
		
		if($emitter=='json') {
			$result_json= json_decode($result);
			if (!is_object($result_json))
			{
				throw new Exception("MerchantOS API Call Error: Could not parse JSON, Response: " . $result);
			}
		} else {
			try
			{
				$result_simplexml = new SimpleXMLElement($result);
			}
			catch (Exception $e)
			{
				throw new Exception("MerchantOS API Call Error: " . $e->getMessage() . ", Response: " . $result);
			}
		}
		
		return $result_simplexml;
	}

Additionally, the function reference to _makeCall within the makeAPICall function must pass the $emitter variable along.

Thanks for the great library.

Dan

**Comment by lukebowerman** [comment]
Thanks Dan - I've integrated your change (https://github.com/merchantos/api_samples/pull/3).

Thanks for contributing and glad you found the sample code useful.

luke
